In [1]:
import pandas as pd
import json
import requests
from pandas.io.json import json_normalize

In [2]:
# Define a function to get info from the FPL API and save to the specified file_path
# It might be a good idea to navigate to the link in a browser to get an idea of what the data looks like
def get_json(file_path, api):
    
    # Post credentials for authentication
    session = requests.session()
    url = 'https://users.premierleague.com/accounts/login/'
    payload = {
     'password': '3l3g4nce',
     'login': 'lee.gower17@gmail.com',
     'redirect_uri': 'https://fantasy.premierleague.com/a/login',
     'app': 'plfpl-web'
    }
    session.post(url, data=payload)
    
    # Call the api and capture the response
    r = session.get(api)
    jsonResponse = r.json()
    with open(file_path, 'w') as outfile:
        json.dump(jsonResponse, outfile)

In [18]:
league_entry_df

,entry_id,entry_name,id,joined_time,player_first_name,player_last_name,short_name,waiver_pick
0,144241,HanksYouAndGoodnight,144429,2019-07-26T13:41:41.866344Z,Benji,Hanks,BH,3
1,173515,RP’s Perks,173794,2019-07-29T14:42:11.017260Z,Rebecca,Perkins,RP,1
2,173968,Wado Wanderers,174248,2019-07-29T15:18:11.896421Z,John,Wadelin,JW,4
3,174011,Liquid Football,174291,2019-07-29T15:22:02.928452Z,James,Fry,JF,5
4,174687,Mein Bergkampf,174967,2019-07-29T16:15:32.391771Z,Liam,Gower,LG,7
5,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
6,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
7,199282,Cocu-doodle-doo,199619,2019-07-31T11:46:55.775220Z,Dave,H,DH,10
8,360260,Auto Pick FC,361492,2019-08-07T08:19:56.900360Z,ben,stuttle,bs,9
9,404268,Beared Goat,405873,2019-08-08T07:27:45.897444Z,Cory,Christman,CC,8

In [17]:
get_json('test_draft_output.json', 'https://draft.premierleague.com/api/league/38996/details')

with open('test_draft_output.json') as json_data:
    d = json.load(json_data)
    print(list(d.keys()))    
    league_entry_df = json_normalize(d['league_entries'])
    matches_df = json_normalize(d['matches'])
    standings_df = json_normalize(d['standings'])

matches_df[matches_df['event'] == 1]

['league', 'league_entries', 'matches', 'standings']

,event,finished,league_entry_1,league_entry_1_points,league_entry_2,league_entry_2_points,started,winning_league_entry,winning_method
0,1,True,197646,46,144429,43,True,None,None
1,1,True,199619,36,177091,30,True,None,None
2,1,True,361492,40,174967,30,True,None,None
3,1,True,405873,69,174291,51,True,None,None
4,1,True,173794,23,174248,68,True,None,None

In [20]:
# Get list of matches with player names
clean_df = pd.merge(matches_df, league_entry_df, left_on='league_entry_1', right_on='id')
clean_df

,event,finished,league_entry_1,league_entry_1_points,league_entry_2,league_entry_2_points,started,winning_league_entry,winning_method,entry_id,entry_name,id,joined_time,player_first_name,player_last_name,short_name,waiver_pick
0,1,True,197646,46,144429,43,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
1,4,True,197646,33,199619,42,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
2,6,True,197646,24,405873,31,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
3,8,True,197646,13,174248,17,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
4,9,True,197646,32,174967,36,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
5,10,True,197646,39,144429,38,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
6,13,True,197646,18,199619,46,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
7,15,True,197646,52,405873,41,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
8,17,True,197646,32,174248,37,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
9,18,True,197646,17,174967,17,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
10,19,False,197646,0,144429,0,True,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
11,22,False,197646,0,199619,0,False,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
12,24,False,197646,0,405873,0,False,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
13,26,False,197646,0,174248,0,False,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
14,27,False,197646,0,174967,0,False,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
15,28,False,197646,0,144429,0,False,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
16,31,False,197646,0,199619,0,False,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
17,33,False,197646,0,405873,0,False,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
18,35,False,197646,0,174248,0,False,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
19,36,False,197646,0,174967,0,False,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
20,37,False,197646,0,144429,0,False,None,None,197313,The Boyz,197646,2019-07-31T09:17:14.244149Z,Huw,Little,HL,2
21,1,True,199619,36,177091,30,True,None,None,199282,Cocu-doodle-doo,199619,2019-07-31T11:46:55.775220Z,Dave,H,DH,10
22,3,True,199619,39,144429,27,True,None,None,199282,Cocu-doodle-doo,199619,2019-07-31T11:46:55.775220Z,Dave,H,DH,10
23,6,True,199619,59,361492,20,True,None,None,199282,Cocu-doodle-doo,199619,2019-07-31T11:46:55.775220Z,Dave,H,DH,10
24,8,True,199619,58,173794,32,True,None,None,199282,Cocu-doodle-doo,199619,2019-07-31T11:46:55.775220Z,Dave,H,DH,10
25,9,True,199619,59,174291,29,True,None,None,199282,Cocu-doodle-doo,199619,2019-07-31T11:46:55.775220Z,Dave,H,DH,10
26,10,True,199619,37,177091,41,True,None,None,199282,Cocu-doodle-doo,199619,2019-07-31T11:46:55.775220Z,Dave,H,DH,10
27,12,True,199619,40,144429,38,True,None,None,199282,Cocu-doodle-doo,199619,2019-07-31T11:46:55.775220Z,Dave,H,DH,10
28,15,True,199619,33,361492,32,True,None,None,199282,Cocu-doodle-doo,199619,2019-07-31T11:46:55.775220Z,Dave,H,DH,10
29,17,True,199619,32,173794,45,True,None,None,199282,Cocu-doodle-doo,199619,2019-07-31T11:46:55.775220Z,Dave,H,DH,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,20,False,174967,0,199619,0,False,None,None,174687,Mein Bergkampf,174967,2019-07-29T16:15:32.391771Z,Liam,Gower,LG,7
161,22,False,174967,0,405873,0,False,None,None,174687,Mein Bergkampf,174967,2019-07-29T16:15:32.391771Z,Liam,Gower,LG,7
162,24,False,174967,0,174248,0,False,None,None,174687,Mein Bergkampf,174967,2019-07-29T16:15:32.391771Z,Liam,Gower,LG,7
163,25,False,174967,0,177091,0,False,None,None,174687,Mein Bergkampf,174967,2019-07-29T16:15:32.391771Z,Liam,Gower,LG,7
164,29,False,174967,0,199619,0,False,None,None,174687,Mein Bergkampf,174967,2019-07-29T16:15:32.391771Z,Liam,Gower,LG,7
165,31,False,174967,0,405873,0,False,None,None,174687,Mein Bergkampf,174967,2019-07-29T16:15:32.391771Z,Liam,Gower,LG,7
166,33,False,174967,0,174248,0,False,None,None,174687,Mein Bergkampf,174967,2019-07-29T16:15:32.391771Z,Liam,Gower,LG,7
167,34,False,174967,0,177091,0,False,None,None,174687,Mein Bergkampf,174967,2019-07-29T16:15:32.391771Z,Liam,Gower,LG,7
168,38,False,174967,0,199619,0,False,None,None,174687,Mein Bergkampf,174967,2019-07-29T16:15:32.391771Z,Liam,Gower,LG,7
169,2,True,177091,39,197646,31,True,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
170,4,True,177091,34,361492,42,True,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
171,6,True,177091,19,173794,33,True,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
172,8,True,177091,29,174291,30,True,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
173,9,True,177091,28,144429,40,True,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
174,11,True,177091,45,197646,14,True,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
175,13,True,177091,40,361492,47,True,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
176,15,True,177091,51,173794,41,True,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
177,17,True,177091,38,174291,64,True,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
178,18,True,177091,31,144429,29,True,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
179,20,False,177091,0,197646,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
180,22,False,177091,0,361492,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
181,24,False,177091,0,173794,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
182,26,False,177091,0,174291,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
183,27,False,177091,0,144429,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
184,29,False,177091,0,197646,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
185,31,False,177091,0,361492,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
186,33,False,177091,0,173794,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
187,35,False,177091,0,174291,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
188,36,False,177091,0,144429,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6
189,38,False,177091,0,197646,0,False,None,None,176805,15 for 1,177091,2019-07-29T19:12:43.420405Z,Thomas,Green,TG,6